Feature/3 入力されたtodoがストックされる機能の追加
bislab-temporary/react-study-sugimizu pull request #4
Opened 2021-10-02 06:39 UTC by ltoppyl

#3 

入力欄に文字を入力  ⇨  Enter  で、入力された文字が下にストックされていく。

【後で実装したい】
- Enterが押されたら入力されてた文字が1回空になる

2021-10-02 07:55 UTC, watagit requested changes
細かい部分で修正が必要そうなところがいくつかありますが、まず、コンポーネントの切り分け方を少し変更したほうがメンテナンス性が格段に上がりそうなのでやってみましょう〜

React のコンポーネントを設計する際に、**単一責任の原則**というのに則っとるのが良いと思います。この原則はざっくり説明すると「1つのコンポーネントは動作や機能を1つのみ持つべきである」というものです。

[React の流儀](https://ja.reactjs.org/docs/thinking-in-react.html)

今回の Todo アプリを例にすると、現状`InputBar`の中に**新しく Todo を作成する機能**と**全ての Todo を表示する機能**の2つが混在しています。
これは単一責任の原則に反していて、もっとキレイにするためには`InputBar`では新しく Todo を作成する機能**だけ**を実装し、別コンポーネントとして`TodoList`(例)を作り、その中で全ての Todo を表示する機能**だけ**を実装する。という形の方が良きです 🙄 

これを踏まえると`App.tsx`はこんな感じになるんじゃないかなと思ってます！（ロジック関連は考慮していない）
```ts
const App = () => {
  return (
    <InputBar />  // ここで新しい Todo を追加
    <TodoList />  // ここで全ての Todo を描画
  )
}
```

2021-10-02 07:55 UTC, watagit commented on todo-app/src/component/InputBar.tsx
> +      />
TodoInput

2021-10-02 07:55 UTC, watagit commented on todo-app/src/component/InputBar.tsx
> +      })}
TodoList

2021-10-02 10:15 UTC, ltoppyl commented
TodoList を1つのコンポーネントとしました。
ついでに、eslint の設定もいろいろ触ったため、そこの変更分もあります。
(これは別のブランチでやればよかったなと途中で思いました)

2021-10-03 05:13 UTC, ltoppyl commented
eslint周りの設定を変更しました。
この部分に関しては無視して下さい。m(_ _)m

2021-10-03 05:37 UTC, ltoppyl commented
今度こそ…m(_ _)m

2021-10-03 07:54 UTC, watagit approved these changes
+1

2021-10-03 07:55 UTC, merged